[site]
url = "https://passport.baidu.com/v2/?login"

[fields]
username = { xpath = "//input[@name='userName']", file='username.txt' }
password = { xpath = "//input[@name='password']", file='password.txt' }

[preactions]
select = { xpath="//p[@title='用户名登录']", action = "click", seq=0 }

[options]
broswer='Firefox'
user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"