[site]
url = "https://accounts.douban.com/passport/login"

[fields]
username = { xpath = "//input[@id='username']", file='username.txt' }
password = { xpath = "//input[@id='password']", file='password.txt' }

[actions]
select_tab = { xpath="//li[@class='account-tab-account']", action = "click", seq=0 }
type_username= {xpath="//input[@id='username']",action="type",form="id",seq=1}
type_password={xpath="//input[@id='password']",action="type",form="password",seq=2}


[options]
broswer='Firefox'
user-agent="Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36"