[site]
url = "https://accounts.douban.com/passport/login"

[fields]
username = { xpath = "//input[@id='username']", file='username.txt' }
password = { xpath = "//input[@id='password']", file='password.txt' }

[preactions]
#TODO
select_tab = { xpath="/html/body/div[1]/div/div/div/div/div[2]/div/div[2]/div/div[1]/div/form/div[1]/div[1]/div[1]/div/div[1]/input", action = "click", seq=0 }

[options]
broswer='Firefox'
user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4389.82 Safari/537.36')"