[site]
url = "https://xui.ptlogin2.qq.com/cgi-bin/xlogin?appid=716027609&daid=383&style=33&login_text=%E7%99%BB%E5%BD%95&hide_title_bar=1&hide_border=1&target=self&s_url=https%3A%2F%2Fgraph.qq.com%2Foauth2.0%2Flogin_jump&pt_3rd_aid=100383922&pt_feedback_link=https%3A%2F%2Fsupport.qq.com%2Fproducts%2F77942%3FcustomInfo%3D.appid100383922&theme=2&verify_theme="

[fields]
username = { xpath = "//*[@id='u']", file='username.txt' }
password = { xpath = "//*[@id='p']", file='password.txt' }

[actions]
select = { xpath="//*[@id='switcher_plogin']", action = "click", seq=0 }
type_username= {xpath="//*[@id='u']",action="type",form="id",seq=1}
type_password={xpath="//*[@id='p']",action="type",form="pw",seq=2}

[options]
broswer='Chrome'
user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"